apiVersion: v1
kind: Service
metadata:
  name: spring-boot-service
spec:
  type: NodePort # NodePort expone el servicio en un puerto est√°tico en cada nodo del cluster. Ideal para acceso local.
  selector:
    app: spring-boot
  ports:
    - protocol: TCP
      port: 8080       # Puerto interno del servicio
      targetPort: 8080   # Puerto del contenedor
      # nodePort: 31000 # Opcional: puedes fijar un puerto o dejar que K8s asigne uno.